dotenv: .env

project_structure:
    build: build
    contracts: contracts
    interfaces: interfaces
    reports: reports
    scripts: scripts
    tests: tests

networks:
  default: mainnet-fork
  mainnet-fork:
    explorer: https://api.etherscan.io/api
    cmd: ganache-cli
    cmd_settings:
      accounts: 50
      mnemonic: brownie
      fork: https://eth-mainnet.alchemyapi.io/v2/$ALCHEMYAPI_TOKEN
      default_balance: 500 ether
      chain_id: 1
  bsc:
    explorer: https://www.bscscan.com/
    host: https://bsc-dataseed1.binance.org
  bsc-fork:
    id: bsc-fork
    cmd: ganache-cli
    host: http://127.0.0.1
    cmd_settings:
      timeout: 120
      accounts: 10
      evm_version: istanbul
      fork: bsc
      gas_limit: 12000000
      mnemonic: brownie
      port: 8545


compiler:
    evm_version: null
    solc:
        version: null
        optimizer:
            enabled: true
            runs: 200
        remappings: null
    vyper:
        version: null

console:
    show_colors: true
    color_style: monokai
    auto_suggest: true
    completions: true
    editing_mode: emacs

reports:
    exclude_paths: null
    exclude_contracts: null
    only_include_project: true

hypothesis:
    deadline: null
    max_examples: 50
    report_multiple_bugs: False
    stateful_step_count: 10
    phases:
        explicit: true
        reuse: true
        generate: true
        target: true
        shrink: true

autofetch_sources: false
dependencies: null
dev_deployment_artifacts: false
